### ISSUE TITLE
Parameters under node  '/devXXXX/triggers/in/* not functional

### ISSUE THREAD

**Issue by simonzihlmann** [zhinst/zhinst-qcodes#16]
Dear ZI qcodes developers,
While using the zhinst-qcodes package, I came across a problem when I tried to access the input impedance of trigger input 1 (see example). I think it is the same for all settings under node `/devXXX/triggers/in/*`. They are not accessible within the zhinst-qcodes package. For example trying to access node '/devXXX/triggers/in/0/imp50' results in a syntax error as shown in the example below:
```
import qcodes as qc
import zhinst.qcodes as ziqc
uhfli = ziqc.UHFLI(name="uhfli", serial="dev2547")
uhfli.triggers.in.in0.imp50()
  File "C:\Users\G-GRE-~1\AppData\Local\Temp/ipykernel_13576/2615439366.py", line 1
    uhfli.triggers.in.in0.imp50()
                   ^
SyntaxError: invalid syntax
```

I assume that  `uhfli.triggers.in.in0.imp50()` should be the good way to query the input impedance of trigger input 1 since the API log shows me `ziDAQ('setInt', '/dev2547/triggers/in/0/imp50', 1)` when setting it to 50 Ohm.

Would it be an option to map the node keyword `in` to `input` or similar to avoid `in`?
Or is there another way to access these setting with the zhinst-qcodes package?

**Comment by tobiasah** [comment]
Thanks for raising this issue. 

We are aware of the problem.
One problem tough is that `in` is a reserved keyword in python so we cannot use it.
But we are planing to implement a proper workaround for this (maybe `input` instead of `in`). 

A workaround until we have fixed would be using the `getattr` function:
`getattr(uhfli.triggers, "in")[0].imp50()`
or 
`getattr(uhfli.triggers, "in").in0.imp50()`


we will keep you updated in this issue about further progress.

**Comment by simonzihlmann** [comment]
Thanks a lot. We are looking forward to a fix. Do you already have an idea when this would happen?

**Comment by tobiasah** [comment]
@simonzihlmann we decided to go with the the PEP8 convention. Meaning appending a tailing underscore to reserved keywords.

> used by convention to avoid conflicts with Python keyword, e.g.:
>
> Tkinter.Toplevel(master, class_='ClassName')

(https://pep8.org/#descriptive-naming-styles)

however the changes are made in zhinst-toolkit and not in qcodes directly. 
Both the toolkit and our QCoDeS driver will have a release within the next month.
