### ISSUE TITLE
Get of parameter immediately following set does not always return newest value. 

### ISSUE THREAD

**Issue by jenshnielsen** [zhinst/zhinst-qcodes#38]
```
from zhinst.qcodes import ZISession
import time
session = ZISession("localhost")

session.connect_device('dev4493')
mfli = session.devices['dev4493']


mfli.oscs[0].freq(11)
time.sleep(0.1)
mfli.oscs[0].freq(100)
print(mfli.oscs[0].freq())
time.sleep(0.1)
print(mfli.oscs[0].freq())
```
results in the following output

```
11.000000057492798
99.99999996068709
```
E.g. if you set a value of a parameter and get it right away it will typically not get the latest value but return the previous value. 
Sleeping for 0.1 sec or so before getting seems to result in the correct value being returned. 

I would expect set on any value to be blocking unless explicitly stated otherwise so this behavior is surprising.

## Versions:

```
zhinst                   22.2.29711
zhinst-deviceutils       0.1
zhinst-qcodes            0.3.4
zhinst-toolkit           0.3.3
```

Tested with both

labone 20.07.23.25
and
22.02.29711 with the same result

**Comment by tobiasah** [comment]
@jenshnielsen Thanks for raising this issue.

LabOne communicates to the device through the DataServer. By default the communication between the PythonAPI(Client) and the Device itself is asynchronous. Meaning setting a value in python (qcodes,toolkit or ziPython directly) only blocks until the value has been acknowledged by the Data Server but not the device itself. 

If one wants a call that blocks until the device has received and acknowledged the new value one has to perform a deep/synchronous set. In toolkit or zhinst-qcodes this can be done with the keyword `deep=True` 

```
from zhinst.qcodes import ZISession
import time
session = ZISession("localhost")

session.connect_device('dev4493')
mfli = session.devices['dev4493']


mfli.oscs[0].freq(11)
mfli.oscs[0].freq(100, deep=True)
print(mfli.oscs[0].freq())
```

should result in 

```
99.99999996068709
```


I hope that answers the question. I am closing this issue. If Something is unclear feel free to reopen it at any time.

**Comment by jenshnielsen** [comment]
Hi @tobiasah The issue is that all other Qcodes instrument apis are normally blocking by default so its very surprising to see one that silently is not.

**Comment by tobiasah** [comment]
Just found the respective documentation of the deep flag.
https://docs.zhinst.com/zhinst-toolkit/en/latest/first_steps/nodetree.html#deep

**Comment by tobiasah** [comment]
@jenshnielsen I can understand your concern that all other common instruments do follow another design. However all devices at Zurich Instruments follow the above mentioned Client->Server->Device(s) design. This design allows high data throughput and efficient parameter changing.

Forcing the default operation to `deep=True` would severely degrade the overall performance of the experiments. Thus we think the default way should be the one offering the maximum performance and flexibility. 

I was thinking of use case for your above mentioned problem but could not find one. Where did you encounter this problem? 

In general I would use a transaction so set multiple parameter in a row. 
```
with device.set_transaction():
    device.demods[0].freq(...)
    device.demods[0].enable(true)
```
This bundles all set requests into a single transaction and guarantees that all parameters have taken effect after it returns.
