### ISSUE TITLE
Connection to HF2LI

### ISSUE THREAD

**Issue by edumur** [zhinst/zhinst-qcodes#4]
Hi all,

I was previously using the old qcodes to connect to my HF2LI as
```python
from qcodes.instrument_drivers.ZI.ZIUHFLI import ZIUHFLI
ZIUHFLI(name='u1', device_ID='DEV405')
```
and it worked great.
I was obtaining the following print
```python
Discovered device `dev405`: HF2LI with options MF, WEB.
Creating an API session for device `dev405` on `127.0.0.1`, `8005` with apilevel `1`.
```

I recently updated my workstation to the new qcodes and I got a deprecated message while using that code
```python 
QCoDeSDeprecationWarning: The class <ZIUHFLI> is deprecated, because There is a new UHFLI driver from Zurich Instruments. Use "instrument_drivers.zurich_instruments.uhfli.UHFLI" as an alternative.
  issue_deprecation_warning(f'{t} <{n}>', reason, alternative)
```

I so used the suggested code and I simply can't connect to the HF2LI anymore.
```python
from  qcodes.instrument_drivers.zurich_instruments.uhfli import UHFLI
UHFLI(name='uhf4',
           serial='dev405',
           interface='USB',
           port=8005,
           api=1)
```

gives me

```python
Successfully connected to data server at localhost:8005 api version: 1
Successfully connected to device DEV405 on interface USB
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-33866b347b0b> in <module>
----> 1 UHFLI(name='uhf4',
      2                    serial='dev405',
      3                    interface='USB',
      4                    port=8005,
      5                 api=1)

~\Anaconda3\lib\site-packages\zhinst\qcodes\uhfli.py in __init__(self, name, serial, interface, host, port, api, **kwargs)
    383         **kwargs,
    384     ) -> None:
--> 385         super().__init__(name, "uhfli", serial, interface, host, port, api, **kwargs)
    386         submodules = self.nodetree_dict.keys()
    387         # initialize submodules from nodetree with blacklist

~\Anaconda3\lib\site-packages\zhinst\qcodes\base.py in __init__(self, name, device_type, serial, interface, host, port, api, **kwargs)
     81                 f"Device type {device_type} is currently not supported in ziQCoDeS. Supported types are {supported_types}"
     82             )
---> 83         self._connect()
     84 
     85     def _connect(self) -> None:

~\Anaconda3\lib\site-packages\zhinst\qcodes\uhfli.py in _connect(self)
    409         )
    410         self._controller.setup()
--> 411         self._controller.connect_device(nodetree=False)
    412         self.connect_message()
    413         self._get_nodetree_dict()

~\Anaconda3\lib\site-packages\zhinst\toolkit\control\drivers\uhfli.py in connect_device(self, nodetree)
     69 
     70         """
---> 71         super().connect_device(nodetree=nodetree)
     72         self._get_streamingnodes()
     73         if "AWG" in self._options:

~\Anaconda3\lib\site-packages\zhinst\toolkit\control\drivers\base\base.py in connect_device(self, nodetree)
    110         if nodetree:
    111             self._nodetree = NodeTree(self)
--> 112         self._options = self._get("/features/options").split("\n")
    113         self._init_settings()
    114 

~\Anaconda3\lib\site-packages\zhinst\toolkit\control\drivers\base\base.py in _get(self, command, valueonly)
    207         """
    208         self._check_connected()
--> 209         return self._controller.get(command, valueonly=valueonly)
    210 
    211     def _get_nodetree(self, prefix: str, **kwargs) -> Dict:

~\Anaconda3\lib\site-packages\zhinst\toolkit\control\connection.py in get(self, command, valueonly)
    487             else:
    488                 data = self._connection.get(node_string, settingsonly=False, flat=True)
--> 489             data = self._get_value_from_dict(data)
    490             if valueonly:
    491                 if len(data) > 1:

~\Anaconda3\lib\site-packages\zhinst\toolkit\control\connection.py in _get_value_from_dict(self, data)
    541             if isinstance(data_dict, list):
    542                 data_dict = data_dict[0]
--> 543             if "value" in data_dict.keys():
    544                 new_data[key] = data_dict["value"][0]
    545             if "vector" in data_dict.keys():

AttributeError: 'str' object has no attribute 'keys'
```

If someone could give me some clue, that would be nice!

**Comment by slaven92** [comment]
Hi @edumur!
I have the same problem now. Did you maybe figure out the solution?

**Comment by edumur** [comment]
Hi @slaven92,

Unfortunately not really.
I contacted ZI directly and this was their reply:

> The old driver, the one in qcodes.instrument_drivers.ZI.ZIUHFLI, was originally written by people in Copenhagen for the UHFLI only. It was working with the HF2LI only by chance on a subset of features. For example the multiple demodulators are not correctly mapped and would fail in many cases.
> Unfortunately in zhinst-qcodes we don’t support the HF2LI since this instrument is quite different from the others and we don’t have short term plans to add it. 
> There is a specific driver for the HF2 maintained by the community, you can find it in the qcodes contrib drivers.
> The zhinst-qcodes is an open source project, so we welcome patches by the community, if you wish to add any functionality in it.
> 

So I went back to the old driver `from qcodes.instrument_drivers.ZI.ZIUHFLI import ZIUHFLI` and ignore the warning.

**Comment by jenshnielsen** [comment]
@edumur Did you have a look at the driver in qcodes contrib drivers? https://github.com/QCoDeS/Qcodes_contrib_drivers/blob/master/qcodes_contrib_drivers/drivers/ZurichInstruments/HF2LI.py 

That one would probably be a better alternative than the one in qcodes since it is not deprecated

**Comment by edumur** [comment]
@jenshnielsen I did and I think it has much less feature.

**Comment by jenshnielsen** [comment]
Ok thanks, do you think it would make sense to port those features over? Or move that driver to contrib drivers and mark it as a HF2LI only driver?

In the long run we would like to remove the UHFLI driver from qcodes since the one in zi-qcodes is more suitable for the UHLFI

**Comment by edumur** [comment]
I do not have a clear reply to this.
The current situation is the following:
1. `qcodes.instrument_drivers.zurich_instruments.uhfli` does not work for the HF2LI.
2. `qcodes.instrument_drivers.ZI.ZIUHFLI` works but is written deprecated.
3. `qcodes_contrib_drivers.drivers.ZurichInstruments.HF2LI` works but, as written in the docstring of the instrument, 
> This driver is meant to emulate a single-channel lockin amplifier,
>so one instance has a single demodulator, a single sigout channel,
> and multiple auxout channels (for X, Y, R, Theta, or an arbitrary manual value).
> Multiple instances can be run simultaneously as independent lockin amplifiers.
> 
> This instrument has a great deal of additional functionality that is
> not currently supported by this driver.".

So we went for 2 since in the end it worked for us...

In the long run I would say that the contrib_driver implements a specific use of the HF2LI which is not general enough compare to what the "official" ZI drivers are offering.
However there is no official driver for the HF2LI and they have no plan to add it.
The only long term solution I see is to mark the HF2LI contrib_driver as the only driver for the HF2LI and to work on it to make it more general.

It is still not perfect though.

**Comment by jenshnielsen** [comment]
Just to clarify `qcodes.instrument_drivers.zurich_instruments.uhfli` is actually an alias to `zhinst.qcodes.uhfli` and lives in this repository. 

What I suggest as a medium term solution is: Take the current uhfli driver from qcodes `qcodes.instrument_drivers.ZI.ZIUHFLI` and copy it to contrib drivers next to the current HF2LI driver. Rename it to something with HF2LI and do whatever easy cleanups can be done and remove the deprecation warning. Then in the future that can be used as a more complete starting point for a new HF2LI driver.

**Comment by edumur** [comment]
Thanks for the precision.
I like your solution!

**Comment by tobiasah** [comment]
Happy to announce that with the latest changes which we now support HF2 devices within out driver. 
We plan to release a new version to pypi next week.
