### ISSUE TITLE
QCoDes will drop Python3.7 support in the future

### ISSUE THREAD

**Issue by markheik** [zhinst/zhinst-qcodes#43]
QCoDes will drop Python3.7 support presumably in version `0.37`. Act according to that.

Source: https://github.com/QCoDeS/Qcodes/pull/3889

**Comment by jenshnielsen** [comment]
@markheik Is that an issue for you? We would like to drop support for 3.7 eventually (mostly since numpy etc. has already dropped support for it) but as you can see from that issue we are willing to postpone it if there are good reasons

**Comment by tobiasah** [comment]
@jenshnielsen no on the contrary. We would be very happy to drop the support for python 3.7. 😀

**Comment by markheik** [comment]
@jenshnielsen Like @tobiasah  said: It is a good thing
