### ISSUE TITLE
missing documentation / release notes

### ISSUE THREAD

**Issue by simonzihlmann** [zhinst/zhinst-qcodes#44]
The last release indicated here on github is 0.3.0 (https://github.com/zhinst/zhinst-qcodes/releases/tag/v0.3), whereas there is version 0.4.0 available on pypi.org (https://pypi.org/project/zhinst-qcodes/). Where can I find the release notes/changelog? Thanks for keeping the documentation up to date.

**Comment by tobiasah** [comment]
Hey @simonzihlmann 

Thanks for bringing this up. 

The latest changelog can be found here https://github.com/zhinst/zhinst-qcodes/blob/main/CHANGELOG.md
or on our documentation page https://docs.zhinst.com/zhinst-qcodes/en/latest/changelog/index.html. It also contains the changes for 0.4.0: 

* Fix Display name for the commandtable node. (`commandtablenode` -> `commandtable`)
* Fix Display name for the awg node. (`awgcore` -> `awg`)

0.4.0 is also available as a tag in GitHub https://github.com/zhinst/zhinst-qcodes/releases/tag/v0.4.0. Compared to 0.3.x it introduces a breaking change (node naming), we therefor decided to bump up the minor version. But we did not create a new release for 0.4.0. Simply for the reason that it does not contain mentionable new feature compared to 0.3.0. I know there are different common practices when to create a new release. I would be curious what your opinion is on this?

**Comment by simonzihlmann** [comment]
@tobiasah I do not have any specific preference nor any experience in that. I just found it strange to have a newer version available without at release on github. For me, github was the place to look for the most recent infos. But I guess all info can be found on https://docs.zhinst.com/zhinst-qcodes (which I did not know before).
