### ISSUE TITLE
synchronous set command (`deep` = True) does not return the acknowledged value

### ISSUE THREAD

**Issue by tobiasah** [zhinst/zhinst-qcodes#47]
LabOne offers two ways of changing a not value. Asynchronous (default) is the fast way. Synchronous (deep=True) blocks until the device has acknowledged the value and there for ensures that the value has been processed by the device before the python execution continuous.

The device acknowledges the value is has processed. Since this value can differ from the input value (e.g. floating point arithmetic, limits ...) it can be important to know this value as an end user. LabOne and toolkit there for returns this value. 
The LabOne QCoDeS driver however does not. 

The problem is that QCoDeS by design does not support returning a value for a set command.

**Comment by jenshnielsen** [comment]
@tobiasah I would suggest that the best solution for doing this in qcodes is to have set explicitly set the cached value of the qcodes parameter with the returned value. That way QCoDeS knowlege of the parameter will be consistent with the state of the instrument. I believe that you should be able to do `self.cache.set(returned_value)`

**Comment by tobiasah** [comment]
@jenshnielsen thanks for the hint. My proposal in #48 is to use `get_wrapper` (in `_wrap_get`)  with the returned value. `get_wrapper` also updates the cache but also considers potential parsers a validators. Thus we do not create a weird state but basically do a set and get in one call at QCoDeS side but only a single call in LabOne. 

Or does this create some unconsidered side effects?

(The ZIParameter tries to a as least invasive as possible to the original Parameter implementation so that one gets the best out of both worlds)

**Comment by jenshnielsen** [comment]
@tobiasah That should be fine as long as its not a significant performance issue to call get again
