### ISSUE TITLE
[UHFQA] Scope submodule blacklisted

### ISSUE THREAD

**Issue by ovaar** [zhinst/zhinst-qcodes#6]
The UHF series has scope support but is blacklisted in the constructor [see](https://github.com/zhinst/zhinst-qcodes/blob/master/zhinst/qcodes/uhfqa.py#L421).

Perhaps this is done for a specific reason. It would be really helpfull to provide an example how to initialize the scope module using zhinst-qcodes without having to modify the sources.

**Comment by tobiasah** [comment]
Thank you for reporting this issue and apologies for responding so late.
The good new is with the new release 0.2.0 that was created just now the the scope module was added to the uhfqa.

If you have any troubles using or accessing it feel free to file a new issue
