### ISSUE TITLE
MFLI validator in qcodes

### ISSUE THREAD

**Issue by FarBo** [zhinst/zhinst-qcodes#7]
Hi,

Qcodes Measurement needs validators for parameters in the measurement. If there is no validator, qcodes interprets it as numeric and perform measurement. This is not problematic until if the output of a parameter is complex. Then measurement won’t run and throws error.
We face this when we want to get value of mfli.demods.demods0.sample in our measurement (The other signals that I checked were not problematic). I tried to dig a bit on this and found out that the unit of sample is ‘dependent’. So, I am not sure if this sample always returns complex or it could also return float. 

At the moment, our users have a work around and that is to validate this parameter before running a measurement, something like this:
mfli.demods.demods0.sample.vals = qcodes.utils.validators.ComplexNumbers()
But, I am looking for implementing a validator inside your driver for this **sample** parameter, if I know it always returns complex or if it is not, we should validate it based on the return value of the parameter. Or you may suggest something else to solve this issue in the driver level.

Thanks

**Comment by tobiasah** [comment]
Thanks for raising this issue.
And also sorry for responding so late. 

demods*.sample always returns a complex number. This is defined in [zhinst-toolkit](https://github.com/zhinst/zhinst-toolkit/blob/4c36a79e3351bf9df6b9c4372c225418aba1157d/src/zhinst/toolkit/control/connection.py#L570)

If I understand it correctly the right way would to add it to our our driver right?
We have created a pull request #8 to solve this issue.

**Comment by FarBo** [comment]
@tobiasah 
Thanks for the reply and the PR.
The approach is to implement it in the driver as you did in the PR.
Would you like me to test the PR as well?

**Comment by tobiasah** [comment]
@FarBo  that would be great if you could test the PR as well.

**Comment by FarBo** [comment]
@tobiasah
I will test it today and confirm in the PR
