### ISSUE TITLE
Logic Error in Qcodes Session Creator?

### ISSUE THREAD

**Issue by samantha-ho** [zhinst/zhinst-qcodes#71]
I believe I've found a logic error in the `ZISession` class which is used to create toolkit sessions for the Qcodes instrument instances.

The error is in the following code block:
```python
        if not new_session:
            for instance in Session.instances():
                if instance.server_host == server_host and (
                    instance.is_hf2_server == hf2
                    or server_port is None
                    or instance.server_port == server_port
                ):
                    return instance
```
If I attempt to instantiate two MFLIs on different ziDataServer ports, and I do not use the `new_session` keyword argument, the `instance.is_hf2_server == hf2` flag causes the 2nd MFLI to end up on the same session and port as the first instance, even though I explicitly set different ports.

If I _do_ use the `new_session` keyword, then I cannot have more than one MFLI on the second ziDataServer port on the same session.

**Comment by mehdialem** [comment]
Thank you, @samantha-ho, for reporting this issue. We are on it and we'll provide the fix as soon as our tests confirm it. 

To better understand your use case, I assume you have multiple MFLIs and you'd like to synchronize them in multiple MDS clusters where each group of MFLIs are synchronized independently from the other groups.

**Comment by samantha-ho** [comment]
That's correct. I have 4-6 MFLIs, and I'd like to sync them in pairs. I received some guidance from a ZI engineer on how to accomplish this, and in implementing their suggestion, ran into this issue.

**Comment by samantha-ho** [comment]
Also, here is a minimal code fragment that reproduces the problem
```python
from zhinst.qcodes import MFLI

mfli1 = MFLI(serial="DEV6890", host="localhost", interface="1GbE", port=8004)
mfli2 = MFLI(serial="DEV6504", host="localhost", interface="1GBE", port=8008)

assert mfli1.session.server_port == 8004
assert mfli2.session.server_port == 8008
```

**Comment by tobiasah** [comment]
We released a new version (https://pypi.org/project/zhinst-qcodes/0.5.5/) which fixes this issue.
If you are still having this or other issues, please don't hesitate to let us know.
